{{- if and .Values.ingress.enabled .Values.ingress.domains }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    {{- if and .Values.ingress.tls.enabled .Values.ingress.tls.clusterIssuer (not .Values.ingress.tls.wildcardSecret) }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.clusterIssuer }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    {{- if .Values.ingress.tls.wildcardSecret }}
    - hosts:
        {{- range .Values.ingress.domains }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.wildcardSecret }}
    {{- else }}
    {{- range .Values.ingress.domains }}
    - hosts: [{{ . | quote }}]
      secretName: {{ include "app.fullname" $ }}-tls-{{ . | replace "." "-" }}
    {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.domains }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.fullname" $ }}
                port:
                  number: {{ $.Values.app.port }}
    {{- end }}
{{- end }}
